anomaly_threshold: 3
anomaly_window_size: 15
avg_window: 30
compute_ad: true
plot_style: line
ra_ad_threshold: 4
ra_ad_window_size: 15
show_anomalies: false
show_avg: true
show_ra_anomalies: true
show_raw: false
window_size: 1000
